### ISSUE TITLE
Invalid private key message on accessing wallet

### ISSUE THREAD

**Issue by aanupam23** [ava-labs/ava-wallet#13]
Suggestion: Invalid private key message if Accessing Wallet using an invalid key

**Checked on Browser**: Firefox, Chrome

**Explanation**
Wallet site allows login using either key file or private key. This issue is related to accessing wallet using private key.
If an invalid private key is used, there is no message or notification regarding invalid key. There should be an "Invalid Key message" if the key used is invalid. 
Example: This is similar to how the faucet shows an error message if using an invalid public key.

**Comment by kanatliemre** [comment]
Added with the new update.
