### ISSUE TITLE
Clickjacking in the wallet website [Security][BugBounty]

### ISSUE THREAD

**Issue by Shashank-In** [ava-labs/ava-wallet#25]
Description:
Instead of giving a copy-paste response, I will add the link 
https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/11-Client_Side_Testing/09-Testing_for_Clickjacking

Impact:
An attacker can iframe the website and gain unwanted clicks over. With level of creativity can allow an attacker to create an iframe change the transparency of the iframe to gain clicks on the website and make a transaction.

Suggested Fix:
Add x-frame-option header and set it to deny or the same origin 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

**Comment by kanatliemre** [comment]
Sorry for the late reply, it's been very busy few weeks. Thank you for noticing this, a fix is on the way.

**Comment by kanatliemre** [comment]
This is fixed with the upcoming updates. Thanks!
